Lab1
Logvynskyy/NodeJS pull request #1
Opened 2022-10-22 16:45 UTC by Logvynskyy

Created by Logvynskyi Stanislav, group IA-03

2022-10-22 16:52 UTC, hxnchar requested changes
Почти лучший

2022-10-22 16:52 UTC, hxnchar commented on .editorconfig
> +insert_final_newline = true
Такс такс такс а где new line?

2022-10-22 16:52 UTC, hxnchar commented on .eslintrc.json
> +    }
New line

2022-10-22 16:52 UTC, hxnchar commented on .github/workflows/main.yaml
> +      uses: actions/cache@v2
cache v3

2022-10-22 17:08 UTC, Logvynskyy commented on .github/workflows/main.yaml
> +      uses: actions/cache@v2
Thank You very much!

2022-10-22 17:08 UTC, Logvynskyy commented on .editorconfig
> +insert_final_newline = true
fixed in the new commit

2022-10-26 21:59 UTC, nosovk commented on .eslintrc.json
> +        "plugin:sonarjs/recommended"
тут стоит еще prettier добавить

2022-10-26 21:59 UTC, nosovk commented on .github/workflows/main.yaml
> +    - name: Cache node modules
после npm ci он как бы уже бесполезен....

2022-10-26 22:00 UTC, nosovk commented on .prettierrc.json
> +    "singleQuote": true,
тут стоит добавить editorconfig: true

2022-10-26 22:00 UTC, nosovk commented
almost

2022-10-30 10:38 UTC, nosovk commented on .github/workflows/main.yaml
> +    - name: Install Everything
тут пропущен  if
сейчас cache-hit игнорируется, и даже есть кеш его npm ci сотрет, и скачает заново.
Нужно запускать npm ci только если кеша нет.

2022-11-20 16:54 UTC, nosovk commented on package.json
> +      "prettier": "prettier src/**/*.ts --check --ignore-path .gitignore",
для преттиера нет нужны в проверке только ts файлов. Если бы он работал только с ts, то мыожно было бы обойтись eslint. Смысл prettier в том что он фомраттер, и умеет форматировать почти что угодно

2022-11-20 16:55 UTC, nosovk commented
поправить преттиер и можно слить

2022-11-20 17:43 UTC, merged